[workspace]
members = [
  "crates/protocol",
  "crates/crypto",
  "crates/server",
  "crates/client",
]

resolver = "3"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
